// vue/LuckyGrid.vue
<template>
	<view class="lucky-box" :style="{ width: boxWidth + 'px', height: boxHeight + 'px' }">
    <canvas id="lucky-canvas" :style="{ width: boxWidth + 'px', height: boxHeight + 'px' }" canvasId="luckyGrid" />
    <view v-if="btnShow">
      <cover-view class="lucky-grid-btn" v-for="(btn, index) in btns" :key="index" @touchstart="toPlay(btn)" :style="{
        top: btn.top + 'px',
        left: btn.left + 'px',
        width: btn.width + 'px',
        height: btn.height + 'px',
      }"></cover-view>
    </view>
    <view v-if="flag !== 'WEB'" class="lucky-imgs">
      <view v-for="(prize, index) in prizes" :key="index">
        <view v-if="prize.imgs">
          <view v-for="(img, i) in prize.imgs" :key="i">
            <image :src="img.src" @load="e => imgBindload(e, 'prizes', index, i)"></image>
            <image :src="img.activeSrc" @load="e => imgBindloadActive(e, 'prizes', index, i)"></image>
          </view>
        </view>
      </view>
    </view>
    <view v-if="flag !== 'WEB'" class="lucky-imgs">
      <view v-for="(btn, index) in buttons" :key="index">
        <view v-if="btn.imgs">
          <image v-for="(img, i) in btn.imgs" :key="i" :src="img.src" @load="e => imgBindload(e, 'buttons', index, i)"></image>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import Taro from '@tarojs/taro'
import { LuckyGrid as Grid } from 'lucky-canvas'
import { changeUnits, resolveImage, getFlag } from '../utils'
export default {
  props: {
    width: { type: [String, Number], default: '600rpx' },
    height: { type: [String, Number], default: '600rpx' },
    cols: { type: [String, Number], default: 3 },
    rows: { type: [String, Number], default: 3 },
    prizes: { type: Array, default: () => [] },
    buttons: { type: Array, default: () => [] },
    blocks: { type: Array, default: () => [] },
    defaultStyle: { type: Object, default () { return {} } },
    activeStyle: { type: Object, default () { return {} } },
    defaultConfig: { type: Object, default: () => { return {} } },
  },
  data () {
    return {
      ctx: null,
      flag: getFlag(),
      $lucky: null,
      boxWidth: 300,
      boxHeight: 300,
      btns: [],
      btnShow: false,
    }
  },
  watch: {
    cols (newData) {
      this.$lucky.cols = newData
    },
    rows (newData) {
      this.$lucky.rows = newData
    },
    blocks (newData) {
      this.$lucky.blocks = newData
    },
    prizes (newData) {
      this.$lucky.prizes = newData
    },
    buttons (newData) {
      this.$lucky.buttons = newData
    },
  },
  mounted () {
    try {
      this.init()
      this.$emit('success')
    } catch (err) {
      this.$emit('error', err)
    } finally {
      this.$emit('finally')
    }
  },
  methods: {
    async imgBindload (res, name, index, i) {
      const img = this[name][index].imgs[i]
      resolveImage(res, img)
    },
    async imgBindloadActive (res, name, index, i) {
      const img = this[name][index].imgs[i]
      resolveImage(res, img, 'activeSrc', '$activeResolve')
    },
    init () {
      this.boxWidth = changeUnits(this.width)
      this.boxHeight = changeUnits(this.height)
      const ctx = this.ctx = Taro.createCanvasContext('luckyGrid', this)
      const $lucky = this.$lucky = new Grid({
        flag: this.flag,
        ctx,
        width: this.boxWidth,
        height: this.boxHeight,
        unitFunc: (num, unit) => changeUnits(num + unit),
        afterDraw: function () {
          ctx.draw()
        },
      }, {
        ...this.$props,
        start: (...rest) => this.$emit('start', ...rest),
        end: (...rest) => this.$emit('end', ...rest),
      })
      // 动态设置按钮大小
      this.$props.buttons.forEach((btn, index) => {
        if (!btn) return
        const [left, top, width, height] = this.$lucky.getGeometricProperty([
          btn.x,
          btn.y,
          btn.col || 1,
          btn.row || 1
        ])
        this.btns[index] = { top, left, width, height }
      })
      this.btnShow = true
    },
    toPlay (btn) {
      this.$lucky.startCallback(btn)
    },
    play (...rest) {
      this.$lucky.play(...rest)
    },
    stop (...rest) {
      this.$lucky.stop(...rest)
    }
  }
}
</script>

<style>
  .lucky-box {
    position: relative;
    overflow: hidden;
  }
  #lucky-canvas {
    position: absolute;
    pointer-events: none;
  }
  .lucky-grid-btn {
    position: absolute;
    background: rgba(0, 0, 0, 0);
    border-radius: 0;
  }
  .lucky-imgs {
    width: 0;
    height: 0;
    visibility: hidden;
  }
</style>

// react/LuckyGrid.js
import React from 'react'
import Taro from '@tarojs/taro'
import { View, Canvas, CoverView, Image } from '@tarojs/components'
import { LuckyGrid as Grid } from 'lucky-canvas'
import { changeUnits, resolveImage, getFlag } from '../utils'
import './index.css'

export default class LuckyGrid extends React.Component {
  ctx = null
  flag = getFlag()
  $lucky = null
  state = {
    boxWidth: 300,
    boxHeight: 300,
    btns: [],
    btnShow: false,
  }
  constructor (props) {
    super(props)
    this.myLucky = React.createRef()
  }
  componentDidMount () {
    const { props } = this
    console.log(props.buttons)
    try {
      this.init()
      props.onSuccess && props.onSuccess()
    } catch (err) {
      console.error(err)
      props.onError && props.onError(err)
    } finally {
      props.onFinally && props.onFinally(err)
    }
  }
  componentDidUpdate (prevProps) {
    if (this.props.cols !== prevProps.cols) {
      this.$lucky.cols = this.props.cols
    }
    if (this.props.rows !== prevProps.rows) {
      this.$lucky.rows = this.props.rows
    }
    if (this.props.blocks !== prevProps.blocks) {
      this.$lucky.blocks = this.props.blocks
    }
    if (this.props.prizes !== prevProps.prizes) {
      this.$lucky.prizes = this.props.prizes
    }
    if (this.props.buttons !== prevProps.buttons) {
      this.$lucky.buttons = this.props.buttons
    }
  }
  async imgBindload (res, name, index, i) {
    const img = this[name][index].imgs[i]
    resolveImage(res, img)
  }
  async imgBindloadActive (res, name, index, i) {
    const img = this[name][index].imgs[i]
    resolveImage(res, img, 'activeSrc', '$activeResolve')
  }
  init () {
    const { props, state } = this
    this.setState({
      boxWidth: changeUnits(props.width),
      boxHeight: changeUnits(props.height)
    })
    let ctx, divElement, flag = this.flag
    if (flag === 'WEB') {
      divElement = this.myLucky.current
    } else {
      ctx = this.ctx = Taro.createCanvasContext('luckyGrid', this)
    }
    this.$lucky = new Grid({
      flag,
      divElement,
      ctx,
      width: state.boxWidth,
      height: state.boxHeight,
      unitFunc: (num, unit) => changeUnits(num + unit),
      afterDraw: function () {
        if (flag === 'WEB') return
        ctx.draw()
      },
    }, {
      ...props,
      start: (...rest) => {
        props.onStart && props.onStart(...rest)
      },
      end: (...rest) => {
        props.onEnd && props.onEnd(...rest)
      }
    })
    // 动态设置按钮大小
    const btns = []
    props.buttons.forEach((btn, index) => {
      if (!btn) return
      const [left, top, width, height] = this.$lucky.getGeometricProperty([
        btn.x,
        btn.y,
        btn.col || 1,
        btn.row || 1
      ])
      btns[index] = { top, left, width, height }
    })
    this.setState({ btns, btnShow: true })
  }
  play (...rest) {
    this.$lucky.play(...rest)
  }
  stop (...rest) {
    this.$lucky.stop(...rest)
  }
  toPlay (btn) {
    this.$lucky.startCallback(btn)
  }
  render () {
    const { props, state } = this
    return this.flag === 'WEB' ? <div ref={this.myLucky}></div> : (
      <View className="lucky-box" style={{ width: state.boxWidth + 'px', height: state.boxHeight + 'px' }}>
        <Canvas id="lucky-canvas" style={{ width: state.boxWidth + 'px', height: state.boxHeight + 'px' }} canvasId="luckyGrid"></Canvas>
        {
          state.btnShow ? <View>
            {
              state.btns.map((btn, index) => <CoverView className="lucky-grid-btn" key={index} onTouchstart={e => this.toPlay(btn)} style={{
                top: btn.top + 'px',
                left: btn.left + 'px',
                width: btn.width + 'px',
                height: btn.height + 'px',
              }}></CoverView>)
            }
          </View> : null
        }
        <View className="lucky-imgs">
          {
            props.prizes.map((prize, index) => <View key={index}>
              {
                prize.imgs ? <View>
                  { prize.imgs.map((img, i) => <View key={i}>
                    <Image src={img.src} onLoad={e => this.imgBindload(e, 'prizes', index, i)}></Image>
                    <Image src={img.activeSrc} onLoad={e => this.imgBindloadActive(e, 'prizes', index, i)}></Image>
                  </View>) }
                </View> : null
              }
            </View>)
          }
        </View>
        <View className="lucky-imgs">
          {
            props.buttons.map((button, index) => <View key={index}>
              {
                button.imgs ? <View>
                  { button.imgs.map((img, i) => <Image key={i} src={img.src} onLoad={e => this.imgBindload(e, 'buttons', index, i)}></Image>) }
                </View> : null
              }
            </View>)
          }
        </View>
      </View>
    )
  }
}

LuckyGrid.defaultProps = {
  width: '600rpx',
  height: '600rpx',
  cols: 3,
  rows: 3,
  blocks: [],
  prizes: [],
  buttons: [],
  defaultStyle: {},
  activeStyle: {},
  defaultConfig: {},
}
